export default [
  { path: '/user', layout: false, routes: [{ path: '/user/login', component: './User/Login' }, {path: '/user/register', component: './User/Register'}] },
  { path: '/', redirect: '/welcome' },
  { path: '/welcome', name: '欢迎', icon: 'smile', component: './Welcome' },
  // { path: '/add_chart_async', name: '智能分析（异步）', icon: 'barChart', component: './AddChartAsync' },
  { path: '/add_chart_mq', name: '智能分析（MQ）', icon: 'barChart', component: './AddChartMq' },
  { path: '/my_chart', name: '历史分析', icon: 'pieChart', component: './MyChart' },
  { path: '/chart_detail/:id', name: '分析详情', icon: 'pieChart', component: './ChartDetail', hideInMenu: true},
  { path: '/order/:id/:type', name: '订单详情', icon: 'pieChart', component: './Order', hideInMenu: true},
  { path: '/chat_with_assistant/:id', name: '聊天助手', icon: 'pieChart', component: './ChatWithAssistant', hideInMenu: true},
  { path: '/ai_chat', name: 'AI辅助分析', icon: 'smileTwoTone', component: './AiChat'},
  { path: '/assistant_list', name: '助手列表', icon: 'barsOutlined', component: './AssistantList' },
  { path: '/user_add_assistant', name: '助手创建中心', icon: 'plusCircleOutlined', component: './UserAddAssistant', hideInMenu: true},
  { path: '/my_info', name: '个人中心', icon: 'userOutlined', component: './MyInfo', hideInMenu: true},
  { path: '/order_detail/:id', name: '订单详情', icon: 'userOutlined', component: './OrderDetail', hideInMenu: true},
  { path: '/shop_list', name: '购物中心', icon: 'shoppingCartOutlined', component: './ShopList'},
  { path: '/order_table', name: '我的订单', icon: 'pieChart', component: './OrderTable'},
  { path: '/ai_assistant_table', name: '助手管理', access: 'canAdmin', icon: 'pieChart', component: './AiAssistantTable'},
  { path: '/product_point_manage', name: '积分商品管理', access: 'canAdmin', icon: 'pieChart', component: './ProductPointManage'},
  { path: '/product_vip_manage', name: '会员商品管理', access: 'canAdmin', icon: 'pieChart', component: './ProductVipManage'},
  {
    path: '/admin',
    icon: 'crown',
    access: 'canAdmin',
    routes: [
      { path: '/admin', name: '管理页面', redirect: '/admin/sub-page' },
      { path: '/admin/sub-page', name: '管理页面2', component: './Admin' },
    ],
  },
  { icon: 'table', path: '/list', component: './TableList' },
  { path: '/', redirect: '/welcome' },
  { path: '*', layout: false, component: './404' },
];

