name: Continuous Deploy #action名称
on: [push] #在推送的时候运行

jobs:
  deploy_job: # 工作名称
    if: contains(github.event.head_commit.message, '#deploy') # 检查提交信息是否包含指定关键词 '#deploy'
    runs-on: ubuntu-latest  #运行环境
    name: build
    steps: # 步骤
      # check out the repository
      - name: Checkout
        uses: actions/checkout@v3    #这里使用了github官方提供的action,checkout项目到虚拟机上
      # 下载依赖，构建项目
      - name: Install Dependencies
        run: yarn #执行的命令
      - name: Build
        run: yarn build
      # 上传dist目录到远程服务器
      - name: Appleboy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # 服务器地址：xxx.xxx.xxx.xxx
          username: 'root' # 服务器名字 一般是root
          key: ${{ secrets.SSH_PRIVATE_KEY }} # 服务器连接密钥
          source: './dist' # 拷贝文件目录
          target: '/home/nginx/html/dataloom-front' # 服务器目标目录
