name: Continuous Deploy #action名称
on: [push] #在推送的时候运行此action

jobs:
  deploy_job: # 工作名称
    runs-on: ubuntu-latest  #运行环境
    name: build
    steps: # 步骤
      # check out the repository
      - name: Checkout
        uses: actions/checkout@v3    #这里使用了github官方提供的action,checkout项目到虚拟机上

      - name: Install Dependencies
        run: yarn #执行的命令
      - name: Build
        run: yarn build

      # 利用action把build好的文件上传到服务器/workspace/react-note路径下,需要确认此目录已在服务端创建
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'   #ssh user name
          server: ${{ secrets.SERVER_HOST }} #引用之前创建好的secret
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} #引用之前创建好的secret
          local_path: './dist/*'  # 对应我们项目build的文件夹路径
          remote_path: './home/nginx/html/dataloom-front'  # 将项目build文件夹部署到远程文件夹
